name: MobBosses
main: boss.BossPlugin
version: 0.1
author: Dolphindalt
description: Mob library recreation.
softdepend: [Carbyne]
commands:
    boss:
        description: Default boss command.
permisions:
    boss.admin:
        description: Admin permissions for the entire plugin.
        default: op